var extend = function(child, parent) {
        for (var key in parent) {
            if (hasProp.call(parent, key)) child[key] = parent[key];
        }

        function ctor() {
            this.constructor = child;
        }
        ctor.prototype = parent.prototype;
        child.prototype = new ctor();
        child.__super__ = parent.prototype;
        return child;
    },
    hasProp = {}.hasOwnProperty;

Router.map(function() {
    return this.route('home', {
        path: "/",
        controller: "homeController"
    });
});

this.homeController = (function(superClass) {
    extend(homeController, superClass);

    function homeController() {
        return homeController.__super__.constructor.apply(this, arguments);
    }

    return homeController;

})(RouteController);

_.extend(Template.home, {
    rendered: function() {
        console.log("home is rendered");
    }
});

// ---
// generated by coffee-script 1.9.2