if (Meteor.isServer) {
    Meteor.startup(function() {
        console.log("Server Starting up...");
        Navigation.remove({});
        Navigation.insert({
            title: "home",
            route: "home"
        });
        Navigation.insert({
            title: "about",
            route: "about"
        });
    });
}

// ---
// generated by coffee-script 1.9.2